core/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    # url(r'^/?$', 'core.views.blank_redirect',
        # name='core_blank_redirect'),
    url(r'^/?$', 'core.views.all_actions',
        name='core_all_actions'),    
    
    url(r'edit-item/(?P<slug>[-\w]+)/?$', 'core.views.edit_item',
        name='core_edit_item'),
        
    url(r'^remove-item/?$', 'core.views.ajax_remove_item',
        name='core_remove_item'),
    
    url(r'^item-list/(?P<status>[-\w]*)/?$', 'core.views.item_list_and_form',
        name='core_item_list_and_form'),
    
    url(r'^item/(?P<slug>[-\w]+)/?$', 'core.views.item_detail',
        name='core_item_detail'),
    
    
        
 
        
    # url(r'^next-actions/?$', 'core.views.next-actions',
        # name='core_next_actions'),
        
    # url(r'^trash/?$', 'core.views.trash',
        # name='core_trash'),
        
    # url(r'^someday-maybe/?$', 'core.views.someday_maybe',
        # name='core_someday_maybe'),
        
    # url(r'^references/?$', 'core.views.references',
        # name='core_references'),
        
    # url(r'^reference/(?P<slug>[-\w]+)?$', 'core.views.next-actions',
        # name='core_next_actions'),
    
        
)

gtd/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gtd.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^accounts/register/?$', 'accounts.views.register', name="register"),
    url(r'', include('core.urls')),
)

core/models.py
from datetime import datetime

from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _

from tinymce.models import HTMLField

from utils.aux_utils import get_image_path, get_file_path, make_hash

from .signal_processors import (create_thumbnail)
from .storage import OverwriteStorage


class Item(models.Model):
    
    IN_BASKET = 1
    IS_PROJECT = 2
    IS_PROJECT_PLAN = 3
    IS_WAITING  = 4
    IN_CALENDAR = 5
    IS_NEXT_ACTION = 6
    IS_TRASH = 7
    IN_SOMEDAY_MAYBE = 8
    IS_REFERENCE = 9
    
    # Options for how to display a post
    
    STATUS_CHOICES = (
        (IN_BASKET, _('In basket')),
        (IS_PROJECT, _('Project')),
        (IS_PROJECT_PLAN, _('Project plan')),
        (IS_WAITING, _('Waiting')),
        (IN_CALENDAR, _('Calendar')),
        (IS_NEXT_ACTION, _('Next action')),
        (IS_TRASH, _('Trash')),
        (IN_SOMEDAY_MAYBE, _('Someday maybe')),
        (IS_REFERENCE, _('Reference')),
    )
    
    
    # Fields representing items content.
    name = models.CharField(max_length=255)
    description = HTMLField(blank=True)
    brief_description = HTMLField(blank=True)
    image = models.ImageField(upload_to=get_image_path, blank=True)
    file = models.ImageField(upload_to=get_file_path, blank=True)
    
    # A reference to project if an instance is one of this project's plans
    # is made available by is_project_plan == True only
    project = models.ForeignKey('self', blank=True, null=True) 
    
    # Categorisation switch
    status = models.IntegerField(choices=STATUS_CHOICES, default=IN_BASKET)
    
    # Helper fields
    slug = models.SlugField(max_length=255, blank=True, unique=True)
    date_added = models.DateTimeField()
    date_updated = models.DateTimeField()
    user = models.ForeignKey(User, null=True)

    class Meta:
        verbose_name = _("Item")
        verbose_name_plural = _("Items")
        
    def __unicode__(self):
        return self.name
    
    
    def save(self, force_insert=False, force_update=False):
        if self.date_added:
            self.date_updated = datetime.now()
        else:
            self.date_added = self.date_updated = datetime.now()
        
        if not self.slug:
            self.slug = slugify(make_hash(self.name, str(self.status)))
        
        if not self.brief_description:
            self.brief_description = self.description[0:255]
            
        super(Item, self).save(force_insert, force_update)
    
    def get_absolute_url(self):
        return reverse('core_item_detail', args=(self.slug,))

core/forms.py
from django.forms import (CharField, ModelForm, Textarea, TextInput,
                          RadioSelect, ClearableFileInput, Select
                          )
from django.utils.translation import ugettext_lazy as _



from .models import Item


class ItemForm(ModelForm):

    """
    ModelForm class to create Item instance.
    """
    #status = forms.IntegerField(widget=forms.)
    
    
    class Meta:
        model = Item
        fields = ['name', 'description', 'image', 'file', 'project', 'status']
        widgets = {
            'name': TextInput(
                attrs={
                    'type':'text',
                    'class':'form-control'
                }
            ),
            'description': Textarea(
                attrs={
                    'cols': 80,
                    'rows': 5,
                    'class':'form-control'
                },
            ),
            'status': RadioSelect(
                choices=Item.STATUS_CHOICES, 
                attrs={
                    #'class': 'form-control'
                }                  
            ),
            'image': ClearableFileInput(
                attrs={
                    'type': 'file',
                    #'class': 'form-control',
                }
            ),
            'file': ClearableFileInput(
                attrs={
                    'type': 'file',
                    #'class': 'form-control',
                }
            ),
            'project': Select(
                choices=Item.objects.values().filter(status=Item.IS_PROJECT),
                attrs={
                    'class': 'form-control',
                }
            )
        }
        
    

core/views.py
import json
from django.core.context_processors import csrf
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from django.template.loader import render_to_string
from django.views.generic import FormView, ListView, DetailView, CreateView
from django.views.generic.edit import ProcessFormView

from .forms import ItemForm
from .models import Item

COLORS = ['success', 'warning', 'danger', 'error', 'info',
          'success', 'warning', 'danger', 'error', 'info']
@login_required
def item_list_and_form(request,
                       status=Item.IN_BASKET,
                       template_name="core/list_and_form.html",
                       action=".",
                       form=None):
    context = {}
    user = request.user
    # If it's POST process a form 
    if request.method == 'POST':
        postdata = request.POST.copy()
        form = ItemForm(postdata)
        context['form'] = form
        if form.is_valid():
            item = form.save(commit=False)
            item.user = user
            item.save()
            status = form.cleaned_data["status"]
    # If it's a get - just rende an object list and an empty form
    else:
        context['form'] = form if form else ItemForm()
        status = check_int(status)
        
    context['object_list'] = Item.objects.values().filter(status=status, user=user)
    context['page_title'] = get_page_title(status)
    context['color'] = COLORS[status-1]
    context['action'] = action
    context.update(csrf(request))
    return render_to_response(template_name, context,
                              context_instance=RequestContext(request))


@login_required
def item_detail(request, slug, template_name="core/item_detail.html"):
    context = {}
    user = request.user
    item = get_object_or_404(Item, slug=slug, user=user)
    # If it's a POST than we have an item  edit
    if request.method == 'POST':
        form = ItemForm(request.POST.copy(), instance=item)
        if form.is_valid():
            form.save()
        kwargs = {'status': check_int(form.cleaned_data["status"]),
                  'form': form}
        
        return item_list_and_form(request, **kwargs)
        
            
    # Otherwise it's a simple GET and we just render a form      
    context["object"] = item
    return render_to_response(template_name, context,
                              context_instance=RequestContext(request))
    
def get_page_title(value):
    for choice in Item.STATUS_CHOICES:
        if choice[0] == value:
            return choice[1]
@login_required            
def all_actions(request, template_name="core/all_actions.html"):
    context = {}
    action_lists = []
    user = request.user
    for choice in Item.STATUS_CHOICES:  
        action_lists.append({"name":choice[1], "actions":[], "color":COLORS[choice[0] - 1]})
        for action in Item.objects.filter(status=choice[0], user=user):
            action_lists[-1]["actions"].append(action)
            
    context["action_lists"] = action_lists            
    return render_to_response(template_name, context,
                              context_instance=RequestContext(request))
    
def blank_redirect(request):
    return HttpResponseRedirect(reverse('core_item_list_and_form', kwargs={'status':1}))

@login_required
def ajax_remove_item(request):
    result = 'False'
    slug = request.REQUEST.get("slug")
    item = Item.objects.get(slug=slug)
    if item:
        item.delete()
        result = 'True'
    
    json_response = json.dumps({'success': result})
    return HttpResponse(json_response, 
                        content_type='application/javascript; charset=utf-8')

def check_int(value):
    # prevent non-int values being passed
    if not isinstance(value, int):
        try: 
            value = int(value)
        except ValueError:
            value = 1
    return value
        
@login_required
def edit_item(request, slug):
    context = {}
    item = Item.objects.get(slug=slug)
    form = None
    if item and request.user == item.user:
        form = ItemForm(instance=item) 
    # template_name = "core/item_form.html"
    # context["form"] = form 
    action = item.get_absolute_url()
    # contex.update(csrf(request))
    return item_list_and_form(request, item.status, form=form, action=action)
    
    
    
    
    
    
    
    
    

templates/core/all_actions.html
{% extends "base.html" %}

{% load core_tags %}

{% block content_wide %}
    <ul class="list-inline">
    {% for list in action_lists %}
        <li class="col-md-4">
            <h3>{{list.name}}</h3>
            {% object_list list.actions list.color %}  
        </li>
    {% endfor %}
    </ul>
    
        
    
{% endblock content_wide %}

templates/core/form_fields.html
{% for field in form %}
<div class="form-group">
    {% if field.errors %}
    <p class="text-error">{{ field.errors }}</p>
    {% endif %}
    <label  for="{{ field.id_for_label }}" class="">{{ field.label }}</label>
    <div class="">
        {{field}}
    </div>
    
</div>
{% endfor %}

templates/core/item_detail.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="well">
    <div class="name">
        <h1><p class="text-info"></p>{{object.name}}</h1>
        <p class="span2">{{object.description}}</p>
        <p class="span2">{{object.description}}</p>
    </div>
</div>
{% endblock content %}

templates/core/item_form.html
<div class="left">
    <form class="form-horizontal" method="post" action="{{action}}" role="form">
        <div class="form-group">
            {% csrf_token %}
            {% include "core/form_fields.html"%}
        </div>
        
        <div class="control">
            <input id="submit_form" type="submit" value="submit" />
        </div>
    </form>
    
</div>

<script type="text/javascript" src="{{STATIC_URL}}js/bootstrap_file_input.js"></script>

templates/core/list_and_form.html
{% extends "base.html" %}

{% load core_tags %}

{% block content %}
<div id="item_form" class="col-md-2 pull-right">
    {% include "core/item_form.html" %}
</div>


<p>{{request.path.split.1}}</p>

<div id="list_wrapper"class="col-md-9 pull-left">
    <h3>{{ page_title }} items</h3>
    {% object_list object_list color %}
</div>

{% endblock %}
{% block content_wide %}
    <div id="scheme" class="col-md-2 pull-left">
        <img src="{{STATIC_URL}}img/gtd-scheme.png" alt=""/>
    </div>
{% endblock content_wide %}
{% block js%}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function(){
            //$("#id_image").addClass("btn btn-warning");
            //$("#id_file").addClass("btn btn-warning");
            $(".file-input-wrapper").addClass("btn-success");
            $("#submit_form").addClass("btn btn-warning");
            $("#id_status").addClass("list-unstyled");
            $("#id_status>li:nth-child(2n)").addClass("pull-right");
            var project_select = $("#id_project");
            project_select.attr("disabled", "disabled");
            $("ul input[name=status]").change(function(){
                var status_radio = $(this);
                
                if (status_radio.attr("value") == "3" ){
                    project_select.removeAttr("disabled");
                }
                else {
                    //var attr = project_select.attr("disabled");
                    //if(typeof attr === 'undefined' && attr === false){
                        project_select.attr("disabled", "disabled");
                        $("#id_project").val("");
                    //}
                }
            });
        });
    </script>
<script src="{{STATIC_URL}}tiny_mce/tiny_mce.js}}"type="text/javascript"></script>
    
{% endblock js%}

templates/core/object_list.html
<div class="">
    <table class="table  table-bordered table-hover table-condensed">
        <thead>
            <th>#</th>
            <th>Name</th>
            <th>Short Descr</th>
            <th>Date added</th>
            <th>Date updated</th>
            <th>Image</th>
            <th>Project</th>
            <th>Actions</th>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr class='{{color}}'>
                {% with slug=object.slug %}
                <td>{{ forloop.counter }}</td>
                <td><a href="{% url 'core_item_detail' slug=slug %}">{{ object.name }}</a></td>
                <td>{{object.brief_description}}</td>
                <td>{{object.date_added}}</td>
                <td>{{object.date_updated}}</td>
                <td>{% if object.image %}
                    <img src="{{object.image.url}}" alt="" style="max-height:100px; width:auto;"/>
                {% endif %}</td>
                <td>
                    {% if object.status == 3 %}
                    <p>{{ object.project.name }}</p>
                    {% endif %}
                </td>
                <td>
                    <button type="button" class="btn btn-default remove_button" data-slug="{{slug}}" >
                        <span class="glyphicon glyphicon-remove"></span>
                    </button>
                    <a href="{% url 'core_edit_item' slug=slug %}" class="btn btn-default edit-link">
                        <span class="glyphicon glyphicon-edit"></span>
                    </a>
                    
                </td>
                {% endwith %}
            </tr>
            {% endfor %}
            
        </tbody>
    </table>
    
</div>